### ISSUE TITLE
Привет, а можн заюзать?

### ISSUE THREAD

**Issue by alexTitakoff** [shanginn/py_telegram_notifier#1]
Тож мысль пришла о таком боте. Но ничего такого найти не мог ;)

Он есть где-т выложенный? чтоб пригласить в чат?

**Comment by shanginn** [comment]
привет)
выложенный он тут и заюзать его можно :)
но чтобы просматривать свои файлы, придётся настраивать его и запускать у себя

**Comment by alexTitakoff** [comment]
неее 
я имею в виду в продакшене есть ? 

разбираться просто не хочется(*сейчас) 
=}

**Comment by alexTitakoff** [comment]
ладн, спасибо ...
)

**Comment by shanginn** [comment]
я так понимаю, ты хочешь, чтобы бот где-то работал, а ты его к себе пригласил в канал?)
суть бота в отправке контента файлов в чат. и если он будет работать где-то, то и файлы он будет брать с этого же сервера, а не у тебя.
какой в этом для тебя прок?
там установка в 4 команды
если будет с ней проблемы - пиши)
